config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  get 'password_resets/new'

  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'sign_up' => 'users#new', as: 'sign_up'
  root to: 'home#index'

  resources :users
  resources :sessions
  resources :password_resets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :password
  before_save :encrypt_password
  before_create { generate_token(:auth_token) }
  attr_accessor :update_mode

  validates_confirmation_of :password
  validates_presence_of :password, length: {minimum: 8, maximum: 255}, on: :update unless update_mode = 'skip_password_validation'
  validates_presence_of :password, length: {minimum: 8, maximum: 255}, on: :create
  validates_presence_of :email, format: { with: /\A.+@[^.].*[a-zA-Z]\z/, message: ' invalid format' }
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def send_password_reset
    update_mode = 'skip_password_validation'
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset
      redirect_to root_url, notice: 'Email sent with password reset instructions.'
    else
      redirect_to new_password_reset_path, alert: 'Email not found'
    end
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.days.ago
      redirect_to new_password_reset_path, alert: 'Password reset has expired.'
    elsif @user.update_attributes(user_params)
      redirect_to root_url, notice: 'Password has been reset!'
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      update_token(user)
      if params[:remember_me]
        # cookies.permanent[:auth_token] = user.auth_token # 20 years cookies
        cookies[:auth_token] = { value: user.auth_token, expires: 1.week.from_now }
      else
        cookies[:auth_token] = { value: user.auth_token, expires: 1.minute.from_now }
      end
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    cookies.delete(:auth_token) #if co
    redirect_to root_url, notice: 'Logged out!'
  end

  def update_token(user)
    user.update_mode = 'skip_password_validation'
    begin
      user.auth_token = SecureRandom.urlsafe_base64
    end while User.exists?(auth_token: user.auth_token)
    user.save!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: 'Signed Up!'
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Smndiaye
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    #user_nav
      - if current_user
        | Logged in as #{current_user.email}.
        |  or
        |  #{link_to "Log out", log_out_path}
      - else
        = link_to "Sign up", sign_up_path
        |  or
        |  #{link_to "log in", log_in_path}
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}"
    = yield

app/views/password_resets/edit.html.slim
= form_for @user, :url => password_reset_path(params[:id]) do |f|
  - if @user.errors.any?
    .error_messages
      h2 Form is invalid
      ul
        - for message in @user.errors.full_messages
          li= message
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions= f.submit "Update Password"

app/views/password_resets/new.html.slim
= form_tag password_resets_path, :method => :post do
  .field
    = label_tag :email
    = text_field_tag :email, params[:email]
  .actions= submit_tag "Reset Password"

app/views/users/new.html.slim
h1 Sign Up
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      h2 Form is invalid
      ul
        - for message in @user.errors.full_messages
          li= message
  p
    = f.label :email
    br/
    = f.text_field :email
  p
    = f.label :password
    br/
    = f.password_field :password
  p
    = f.label :password_confirmation
    br/
    = f.password_field :password_confirmation
  p.button= f.submit